---
deployment:
  tasks:
    - /bin/mkdir -p /home/mpetechn/mpe-staging-app/tmp
    - /bin/rm -rf /home/mpetechn/mpe-staging-app/dist
    - /bin/rm -rf /home/mpetechn/mpe-staging-app/public
    - /bin/rm -f /home/mpetechn/mpe-staging-app/server.js
    - /bin/rm -f /home/mpetechn/mpe-staging-app/package.json
    - /bin/cp -a deploy/shinjiru-runtime/dist /home/mpetechn/mpe-staging-app/dist
    - /bin/cp -a deploy/shinjiru-runtime/public /home/mpetechn/mpe-staging-app/public
    - /bin/cp deploy/shinjiru-runtime/server.js /home/mpetechn/mpe-staging-app/server.js
    - /bin/cp deploy/shinjiru-runtime/package.json /home/mpetechn/mpe-staging-app/package.json
    - /bin/cp deploy/shinjiru-runtime/tmp/deployment.txt /home/mpetechn/mpe-staging-app/tmp/deployment.txt
    - touch /home/mpetechn/mpe-staging-app/tmp/restart.txt
