---
deployment:
  tasks:
    - source /home/mpetechn/nodevenv/mpe-staging-app/24/bin/activate && npm ci --include=dev
    - source /home/mpetechn/nodevenv/mpe-staging-app/24/bin/activate && npm run build
    - /bin/mkdir -p /home/mpetechn/mpe-staging-app/tmp
    - /bin/rm -rf /home/mpetechn/mpe-staging-app/dist /home/mpetechn/mpe-staging-app/public
    - /bin/cp -a dist/standalone/dist /home/mpetechn/mpe-staging-app/dist
    - /bin/cp -a dist/standalone/public /home/mpetechn/mpe-staging-app/public
    - /bin/cp dist/standalone/server.js /home/mpetechn/mpe-staging-app/server.js
    - /bin/cp deploy/shinjiru-package.json /home/mpetechn/mpe-staging-app/package.json
